# Generated by Django 2.1.5 on 2019-11-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroupimage',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
    ]
